# Generated by Django 5.1.3 on 2024-12-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platfroms',
            new_name='platforms',
        ),
    ]
